name: Pterodactyl-Panel
version: '${project.version}'
main: de.realzone.panel.Main
api-version: 1.13

commands:
  panel:

permissions:
  pterodactyl.panel.open:
    description: Opens the Panel
    default: op
  pterodactyl.panel.gui.server:
    description: Opens the Server GUI
    default: op
  pterodactyl.panel.gui.user:
    description: Opens the User GUI
    default: op